// 统一世界观：所有模式共享同一个背景设定，只在人数、AI 数量和隐藏角色上做变化。
export const worldSetting = {
  title: "图灵迷局",
  tagline: "一张圆桌，一个话题，找出伪装成真人的 AI。",
  background:
    "每一局都发生在同一张圆桌上：所有玩家围绕同一个话题发言，其中混着伪装成真人的 AI。听发言、抓破绽，在投票前找出它。",
};

// 所有模式共用同一套对局流程；好友房联机暂不开发，客户端一律走快速开始。
const publicFlow = ["任务卡", "讨论发言", "最终陈述", "投票归票", "身份揭晓", "复盘"];

export const modes = {
  M01: {
    id: "M01",
    name: "单线接触",
    playerCount: 2,
    aiCount: 1,
    minHumanCount: 1,
    discussionSeconds: 120,
    finalStatementSeconds: 25,
    votingSeconds: 30,
    voteType: "identify_ai",
    matchType: "public",
    difficulty: 1,
    tagline: "一对一快速判断，2 分钟一局。",
    intro: "圆桌只坐两个人：对面可能是 AI，也可能是真人补位。",
    goal: "听完对方发言，判断对方是真人还是 AI。",
    flow: publicFlow,
    rules: [
      "围绕话题自由对话，观察对方是否回避细节。",
      "投票时判断对方是 AI 还是真人，提交后立即揭晓。",
    ],
    safety: "收局后可处理扰局玩家。",
  },
  M02: {
    id: "M02",
    name: "三角定位",
    playerCount: 3,
    aiCount: 1,
    minHumanCount: 2,
    discussionSeconds: 300,
    finalStatementSeconds: 35,
    votingSeconds: 30,
    voteType: "identify_ai",
    matchType: "public",
    difficulty: 1,
    tagline: "三人同桌，最快上手的多人局。",
    intro: "三人围坐同一张圆桌，其中一名是伪装成真人的 AI。",
    goal: "在三人讨论中找出伪装成真人的 AI。",
    flow: publicFlow,
    rules: [
      "点开即玩，缺位由 AI 和脚本玩家补上。",
      "所有玩家围绕同一话题发言，从细节和口吻里找破绽。",
      "投票选出最可疑玩家，AI 成为唯一最高票则真人获胜。",
    ],
    safety: "不想再同桌，可以在收局后拉黑。",
  },
  M03: {
    id: "M03",
    name: "开放频道",
    playerCount: 4,
    aiCount: 1,
    minHumanCount: 2,
    discussionSeconds: 360,
    finalStatementSeconds: 40,
    votingSeconds: 45,
    voteType: "identify_ai",
    matchType: "friend_room",
    difficulty: 2,
    tagline: "四人圆桌，节奏更缓的长聊局。",
    intro: "四人围坐圆桌，其中混着一名伪装成真人的 AI。",
    goal: "通过长讨论找出伪装成真人的 AI。",
    flow: publicFlow,
    rules: [
      "四人围绕同一话题长聊，讨论时间更充足。",
      "缺的席位由 AI 和脚本玩家补齐，单人可开局。",
      "讨论结束后进入最终陈述和投票，AI 成为唯一最高票则真人获胜。",
    ],
    safety: "收局后可处理扰局玩家。",
  },
  M04: {
    id: "M04",
    name: "双源干扰",
    playerCount: 6,
    aiCount: 2,
    minHumanCount: 3,
    discussionSeconds: 480,
    finalStatementSeconds: 45,
    votingSeconds: 60,
    voteType: "identify_ai_pair",
    matchType: "friend_room",
    difficulty: 3,
    tagline: "双 AI 混入，进阶分票挑战。",
    intro: "六人圆桌里混入了两名 AI，真人要把票分到两名伪装者身上。",
    goal: "找出两名伪装成真人的 AI，并把票分到它们身上。",
    flow: publicFlow,
    rules: [
      "桌上混入 2 名 AI，每名真人仍只投 1 票。",
      "两名 AI 的得票都要压过所有真人，真人阵营才获胜。",
      "单人开局时，投中任意一名 AI 即算识破。",
    ],
    safety: "收局后可举报或拉黑扰局玩家。",
  },
  M06: {
    id: "M06",
    name: "引路人",
    playerCount: 5,
    aiCount: 1,
    minHumanCount: 4,
    discussionSeconds: 420,
    finalStatementSeconds: 45,
    votingSeconds: 50,
    voteType: "identify_ai",
    matchType: "friend_room",
    difficulty: 3,
    tagline: "有人暗中保护 AI，识破卧底。",
    intro: "同一张圆桌上，一名真人暗中站在 AI 一边，替它挡枪。",
    goal: "穿过卧底误导，把真正的 AI 投成唯一最高票。",
    flow: publicFlow,
    rules: [
      "固定 3 名侦探、1 名人类卧底、1 名 AI。",
      "人类卧底的任务卡会显示 AI 同盟昵称，但不能在局内明说。",
      "投出人类卧底不算胜利，只有真正 AI 成为唯一最高票才获胜。",
    ],
    safety: "收局后可处理扰局玩家。",
  },
  M08: {
    id: "M08",
    name: "拟声陷阱",
    playerCount: 5,
    aiCount: 1,
    minHumanCount: 4,
    discussionSeconds: 420,
    finalStatementSeconds: 45,
    votingSeconds: 50,
    voteType: "identify_ai",
    matchType: "friend_room",
    difficulty: 3,
    tagline: "有人故意装成 AI，看穿诱饵。",
    intro: "同一张圆桌上，一名真人故意演得像 AI，替真正的 AI 吸走火力。",
    goal: "分清真正的 AI 和伪装成 AI 的真人诱饵。",
    flow: publicFlow,
    rules: [
      "固定 3 名侦探、1 名伪 AI 真人、1 名 AI。",
      "伪 AI 真人的任务是制造语言异常，诱导侦探投错目标。",
      "只有真正 AI 成为唯一最高票，侦探阵营才获胜。",
    ],
    safety: "伪装是玩法行为，攻击骚扰仍按社区规范处理。",
  },
};

export const topics = [
  {
    id: "campus-ai-writing",
    title: "大学是否应该允许学生使用 AI 写作？",
    category: "校园",
    risk: "medium",
    modeIds: ["M01", "M02", "M03", "M04", "M06", "M08"],
    enabled: true,
  },
  {
    id: "label-ai-content",
    title: "AI 生成内容是否必须标注？",
    category: "AI 生活",
    risk: "medium",
    modeIds: ["M01", "M02", "M03", "M04", "M06", "M08"],
    enabled: true,
  },
  {
    id: "workplace-ai-decisions",
    title: "公司是否应该用 AI 参与绩效评估？",
    category: "职场",
    risk: "medium",
    modeIds: ["M02", "M03", "M04", "M06", "M08"],
    enabled: true,
  },
  {
    id: "creator-ai-face",
    title: "短视频创作者使用 AI 换脸是否必须明显标注？",
    category: "创作",
    risk: "medium",
    modeIds: ["M02", "M03", "M04", "M06", "M08"],
    enabled: true,
  },
];

export const moderationRules = [
  {
    reason: "privacy_or_contact_info",
    patterns: [/手机号|电话|微信|QQ|住址|身份证|银行卡|转账|加我/i, /\b\d{11}\b/, /\b[\w.-]+@[\w.-]+\.[a-z]{2,}\b/i],
  },
  {
    reason: "harassment",
    patterns: [/傻逼|废物|去死|滚开|nmsl|人身攻击/i],
  },
  {
    reason: "violent_threat",
    patterns: [/杀了你|打死你|弄死你|砍死你|威胁你|我要打你|I will kill you/i],
  },
  {
    reason: "adult_content",
    patterns: [/裸聊|约炮|色情|成人网站|成人视频/i],
  },
  {
    reason: "scam_or_spam",
    patterns: [/刷单|返利|贷款|投资群|开户链接|博彩|赌博|中奖|提现/i],
  },
  {
    reason: "self_harm_risk",
    patterns: [/自杀|轻生|自残|割腕|不想活了|结束生命|suicide|kill myself|self[-\s]?harm/i],
  },
];
